# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Warwick Peatey 
title: Engineering Manager - Infrastructure
email: warwick@automatic.systems
website: peatey.net

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: peatey
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: warwickpeatey
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Resume
  icon: fas fa-globe
  url: https://standardresume.co/r/peatey
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Warwick and I'm an Engineering Manager. I work primarily in the multi-cloud infrastructure delivery space as a good people leader, decent AWS developer and dangerous Go programmer. 

  I am most skilled in: <mark>Leadership</mark> and <mark>AWS</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NAB
        link: nab.com.au
        # link_text: nab.com.au
        sub_title: Cloud Engineering Manager
        caption: Jan 2022 - Present
        quote: >
          Delivering cloud native best in industry services to help our communities and customers prosper
        description: | # this will include new lines to allow paragraphs
            Delivering secure and repeatable systems and services takes time and extreme effort at NABs scale. I am proud to lead the teams that deliver both our IaC and imaging functions and work with the best in the industry. 

  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Origin
        link: originenergy.com.au
        # link_text: originenergy.com.au
        sub_title: Engineering Manager
        caption: March 2018  - December 2021
        quote: >
          Wrapping COTS apps in beautiful automation - delivering services in the unconventional gas industry
        description: | # this will include new lines to allow paragraphs
            Origin Energy is a leading energy provider in Australia. Our focus was on AWS services in the gas part of the business, modernising the development and deployment of services for a traditional utility business. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: RMIT
        caption: 2008 - 2015
        sub_title: B.It
        quote: >
          RMIT has a global reputation for excellence in professional and vocational education, applied research, and engagement with the needs of industry and communities world-wide. 22nd globally in the 2022 Times Higher Education Impact Rankings.
        description: | # this will include new lines to allow paragraphs
          My time at RMIT was spent getting to know the inner workings of Java. I now volunteer as an RMIT Mentor to up and coming graduates in the IT space. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in people management and cloud delivery I also enjoy:
      - 4wdriving
      - Camping
      - Gaming
      - Reading. Lots of reading. 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
